### PR TITLE
Added memory map from multiboot

### PR DESCRIPTION
**Pull request by jcmnn**
This pulls the memory map from the bootloader and sorts it from smallest address to greatest. This will be used for paging but I'm not sure which method you want to use for paging (stack, buddy system, etc).

### CODE REVIEW

**Comment by feliwir** [comment]
Sorry, missed this. Will check tomorrow!

**Comment by feliwir** [comment]
I need to investigate further into paging before i can merge this, sorry. :(

**Comment by jcmnn** [comment]
That's fine, no rush!

**Comment by feliwir** [comment]
Looks good to me

**Comment by feliwir** [comment]
@Altenius actually for me there is never a tag 6 processed :(

**Comment by feliwir** [comment]
I fixed it. The issue was wrong pointer arithmetic

**Pull request merged**
