### PR TITLE
Optimized string functions and fixed travis build

### PR DESCRIPTION
**Pull request by jcmnn**

### CODE REVIEW

**Review by feliwir — COMMENTED** [review]
hey, thanks for your PR. Is the x64 IDT working fot you?

**Comment by jcmnn** [comment]
No, I just realized it's not.

**Comment by feliwir** [comment]
Yeah, that’s where i got stuck... I might want to take a deeper look again

**Comment by jcmnn** [comment]
I disabled the IDT initialization and it still crashed so it's likely an issue with the GDT.

**Comment by feliwir** [comment]
Yeah the gdt is wrong, that’s why the IDT didn’t work.

**Pull request merged**
